steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'jeetendra@instance-2'
  - '--zone'
  - 'us-central1-a'
  - '--command'
  - |
    cd /home/jeetendra/workspace
    git clone https://github.com/Jeetendradwivedi21/todousingcloudsql.git
    cd /home/jeetendra/workspace/todousingcloudsql
    go mod init github.com/jeetendradwivedi21/todousingcloudsql
    go mod tidy
    go build main.go
    ./main

options:
  logging: 'CLOUD_LOGGING_ONLY'
