steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'jeetendra@instance-2'
  - '--zone'
  - 'us-central1-a'
  - '--command'
  - |
    cd /home/jeetendra/todousingcloudsql
    go mod tidy
    go version
    go build -o main main.go
    ls -l
    ./main

options:
  logging: 'CLOUD_LOGGING_ONLY'
