steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'root@instance-2'
  - '--zone'
  - 'us-central1-a'
  - '--command'
  - 'ls /home/jeetendra/todousingcloudsql/main.go'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CORE_PROJECT=handy-zephyr-403110'
options:
  logging: 'CLOUD_LOGGING_ONLY'
