steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'jeetendra@instance-2'
  - '--zone'
  - 'us-central1-a'
  - '--command'
  - |
    sudo apt-get update
    sudo apt-get install -y golang

    cd /home/jeetendra/todousingcloudsql
    go build main.go
    ./main

options:
  logging: 'CLOUD_LOGGING_ONLY'
substitutions:
  _CLOUDSDK_COMPUTE_ZONE: 'us-central1-a'
  _CLOUDSDK_CORE_PROJECT: 'handy-zephyr-403110'
