steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'jeetendra@instance-2'
  - '--zone'
  - 'us-central1-a'
  - '--command'
  - |
    cd /home/jeetendra/todousingcloudsql
    go build main.go
    ./main

options:
  logging: 'CLOUD_LOGGING_ONLY'
env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CORE_PROJECT=handy-zephyr-403110'
