steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'jeetendra@instance-2'
  - '--zone'
  - 'us-central1-a'
  - '--command'
  - |
    cd /home/jeetendra/todousingcloudsql
    go mod tidy
    go version  # Print Go version for debugging
    go build -o main main.go
    ls -l         # List files in the current directory for debugging
    ./main
