steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'jeetendra@instance-2'
  - '--zone'
  - 'us-central1-a'
  - '--command'
  - |
    cd /home/jeetendra/todousingcloudsql
    go mod tidy
    go version
    go build -o /home/jeetendra/todousingcloudsql/main.go
    ls -l
    /home/jeetendra/todousingcloudsql/main

options:
  logging: 'CLOUD_LOGGING_ONLY'
  logStreamingOption: 'STREAM_ON'  # Use 'STREAM_OFF' if you don't want streaming logs
